/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ProblemDetails;
import org.openapitools.client.model.Solicitud;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SolicitudApi
 */
@Disabled
public class SolicitudApiTest {

    private final SolicitudApi api = new SolicitudApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void solicitudComprobarSolicitudGetTest()  {
        // uncomment below to test the function
        //String nombreUsuario = null;
        //Integer tok = null;
        //List<Integer> response = api.solicitudComprobarSolicitudGet(nombreUsuario, tok).collectList().block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void solicitudGetSolicitudesUsuarioGetTest()  {
        // uncomment below to test the function
        //String nombreUsuario = null;
        //List<Integer> response = api.solicitudGetSolicitudesUsuarioGet(nombreUsuario).collectList().block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void solicitudSolicitarPostTest()  {
        // uncomment below to test the function
        //String nombreUsuario = null;
        //Solicitud solicitud = null;
        //Object response = api.solicitudSolicitarPost(nombreUsuario, solicitud).block();

        // TODO: test validations
    }
    
}
